name: Build and push package to npm on merge to 'main'

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
